name: Build Android APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get the code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Make Gradle executable
      run: chmod +x ./gradlew

    - name: Build the APK (Bypassing checks)
      run: ./gradlew assembleDebug -x check -x detekt -x ktlintCheck

    - name: Upload the APK
      uses: actions/upload-artifact@v4
      with:
        name: TV-Receiver-APK
        path: app/build/outputs/apk/debug/*.apk
